In [2]:
import numpy as np

In [2]:
l = np.array([[[[[1,2,3]]]]])
print(l.shape)

(1, 1, 1, 1, 3)


In [13]:
d0 = ()
d1 = (1,2,3,4)
d2 = [[1,2],
      [3,4]]
d3 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
d4 = [[[[[1,2,3]]]]]
d_not = [[1, 2], [3]]

print(np.array(d0).shape)
print(np.array(d1).shape)
print(np.array(d2).shape)
print(np.array(d3).shape)
print(np.array(d4).shape)
print('#' * 10)
print(np.array(d0).dtype)
print(np.array(d1).size)
print(np.array(d2).size)
print(np.array(d3).size)
print(np.array(d4).size)
# print(np.array(d_not).size)

# print(np.array(d_not).shape)

(0,)
(4,)
(2, 2)
(2, 2, 2)
(1, 1, 1, 1, 3)
##########
float64
4
4
8
3


In [10]:
d = {1: 'one', 2: 'two'}
np.array(d)

array({1: 'one', 2: 'two'}, dtype=object)

In [ ]:
def fact(n):
  
  if n == 1:
    return 1
  
  return n * fact(n-1)


print(fact(5))

120


In [68]:
def arr_shape(List, shape = None):

  if shape is None:
    shape = []

  if not isinstance(List, list) or not List:
    return shape
  
  shape.append(len(List))
  
  return arr_shape(List[0], shape)

print(arr_shape(d1))
print(arr_shape(d2))
print(arr_shape(d3))
print(arr_shape(d_not))

[4]
[2, 2]
[1, 2, 3]
[2, 2]


In [11]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
l = [1, 2, 3]
l2 = [[1, 2], [3, 4]]

def flatten(l):
  print(l)
  if not l:
    return None
  
  if not (isinstance(l, list)):
      return None
  return flatten(l[0])

flatten(l)
flatten(l2)

[1, 2, 3]
1
[[1, 2], [3, 4]]
[1, 2]
1


In [1]:
import numpy as np

In [10]:
print(np.zeros((2,3, 3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
